#include <string>
#include <boost/any.hpp>
#include <boost/numeric/ublas/matrix.hpp>
#include <boost/numeric/ublas/vector.hpp>
#include <sdp_prob.hpp>
#include <nana.h>
#include <sdp_wrapper.hpp>
#include <factory/factory.h>
#include <configuration.hpp>
